{% set name = "geospark" %}
{% set version = "1.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geospark-{{ version }}.tar.gz
  sha256: ab6157297f6d395001305b1e21f1a4cca75e169c704b3de998bbc260095900a3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - attrs
    - findspark
    - pyspark
    - python >={{ python_min }}
    - shapely

test:
  requires:
    - python {{ python_min }}
  imports:
    - geospark
    - geospark.core

about:
  home: https://github.com/DataSystemsLab/GeoSpark/tree/master/python
  summary: GeoSpark Python
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: APACHE
  doc_url: http://sedona.apache.org/
  dev_url: https://github.com/apache/incubator-sedona

extra:
  recipe-maintainers:
    - JennaLipscomb
    - oblute
